<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ApplicationEntryPoint>SelfCOMServer.App</ApplicationEntryPoint>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <CsWinRTIncludes>SelfCOMServer.Metadata</CsWinRTIncludes>
    <DefaultLanguage>en-US</DefaultLanguage>
    <DefineConstants>$(DefineConstants);DISABLE_XAML_GENERATED_MAIN</DefineConstants>
    <EnableMsixTooling>True</EnableMsixTooling>
    <OutputType>WinExe</OutputType>
    <Platforms>x86;x64;ARM64</Platforms>
    <PublishAot>True</PublishAot>
    <PublishProfile>win-$(Platform).pubxml</PublishProfile>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.16299.0</TargetPlatformMinVersion>
    <UseUwp>True</UseUwp>
    <VersionPrefix>0.0.1</VersionPrefix>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.183" PrivateAssets="all">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Windows.CsWinRT" Version="2.2.0" />
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <ItemGroup>
    <CsWinRTInputs Include="..\WinMD\$(Platform)\$(Configuration)\SelfCOMServer.Metadata.winmd" />
    <Content Include="..\WinMD\$(Platform)\$(Configuration)\SelfCOMServer.Metadata.winmd" Visible="False">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\WinRTWrapper\WinRTWrapper.SourceGenerators\WinRTWrapper.SourceGenerators.csproj">
      <OutputItemType>Analyzer</OutputItemType>
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <SetTargetFramework>TargetFramework=netstandard2.0</SetTargetFramework>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <None Remove="AppPackages\**" />
    <None Remove="BundleArtifacts\**" />
  </ItemGroup>
</Project>