namespace SelfCOMServer.Metadata
{
    [contractversion(1)]
    apicontract SelfCOMServerContract{};

    [contract(SelfCOMServerContract, 1)]
    interface IRemoteThing
    {
        String SayHello();
    }
}